version: 'serverexpress1'

services:
  # Aplicación en React
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    command: yarn dev
    environment:
      - NODE_ENV=development

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/server
      - /usr/src/server/node_modules
    command: yarn start
    depends_on:
      - databaseavg

  databaseavg:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "expressjsavg"
      POSTGRES_PASSWORD: "secret"

    container_name: "dataavg"
    volumes:
      - ./postgres:/var/lib/postgresql/data

#ESTE ARCHIVO ES PARA USO DE LA APLICACION LOCAL EN DOCKER.COMPOSE USANDO LOS COMANDOS DE :
#COMANDO PARA EJECUTAR DOCKER.COMPOSE.YML
#docker-compose up --build
