version: 'serverexpress1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: nodemon server/index.js
    depends_on:
      - databaseavg

  databaseavg:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "expressjsavg"
      POSTGRES_PASSWORD: "secret"

    container_name: "dataavg"
    volumes:
      - ./postgres:/var/lib/postgresql/data

#ESTE ARCHIVO ES PARA USO DE LA APLICACION LOCAL EN DOCKER.COMPOSE USANDO LOS COMANDOS DE :
#COMANDO PARA EJECUTAR DOCKER.COMPOSE.YML
#docker-compose up --build
